[package]
name = "as4"
version = "0.1.0"
authors = ["m-mueller678"]

[dependencies]
mio = "0.6.2"
log = "0.3.6"
env_logger = "0.3.5"
serde = "0.8.22"
serde_derive = "0.8.22"
serde_json = "0.8.4"
rand = "0.3.15"

[[bin]]
name = "server"
path = "src/server_main.rs"