[package]
name = "server"
version = "0.1.0"
authors = ["m-mueller678"]

[dependencies]
mio = "0.6.2"
log = "0.3.6"
env_logger = "0.3.5"
serde = "0.8.22"
rand = "0.3.15"
protocol = {path = "../protocol"}
